os:
  - linux

language: php

php:
  - '7.3'

before_script:
  - composer self-update
  - composer install --no-interaction
  - nvm install 7.7.1
  - npm install npm@latest -g
  - npm install

script:
  - npm run production
